#############################################################################
# Makefile for building: TestSetCreator.app/Contents/MacOS/TestSetCreator
# Generated by qmake (3.1) (Qt 5.12.6)
# Project:  TestSetCreator.pro
# Template: app
# Command: /Users/adrian/Qt/5.12.6/clang_64/bin/qmake -o Makefile TestSetCreator.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I../Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt/5.12.6/clang_64/mkspecs/macx-clang -F/Users/adrian/Qt/5.12.6/clang_64/lib
QMAKE         = /Users/adrian/Qt/5.12.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/adrian/Qt/5.12.6/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/adrian/Qt/5.12.6/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TestSetCreator1.0.0
DISTDIR = /Users/adrian/TestSetCreator/.tmp/TestSetCreator1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/adrian/Qt/5.12.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/adrian/Qt/5.12.6/clang_64/lib -L/usr/local/lib -ljpeg -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		masterjpeg.cpp \
		picturedisplay.cpp moc_mainwindow.cpp \
		moc_masterjpeg.cpp \
		moc_picturedisplay.cpp
OBJECTS       = main.o \
		mainwindow.o \
		masterjpeg.o \
		picturedisplay.o \
		moc_mainwindow.o \
		moc_masterjpeg.o \
		moc_picturedisplay.o
DIST          = ../Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.12.6/clang_64/mkspecs/qdevice.pri \
		../Qt/5.12.6/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.12.6/clang_64/mkspecs/common/unix.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/mac.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/macx.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/clang.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.12.6/clang_64/mkspecs/qconfig.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/qt.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/resources.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/moc.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/uic.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/lex.prf \
		TestSetCreator.pro mainwindow.h \
		masterjpeg.hpp \
		picturedisplay.hpp main.cpp \
		mainwindow.cpp \
		masterjpeg.cpp \
		picturedisplay.cpp
QMAKE_TARGET  = TestSetCreator
DESTDIR       = 
TARGET        = TestSetCreator.app/Contents/MacOS/TestSetCreator

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/adrian/TestSetCreator/TestSetCreator.pro


include /Users/adrian/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

TestSetCreator.app/Contents/MacOS/TestSetCreator: ui_mainwindow.h $(OBJECTS)  
	@test -d TestSetCreator.app/Contents/MacOS/ || mkdir -p TestSetCreator.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TestSetCreator.pro ../Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.12.6/clang_64/mkspecs/qdevice.pri \
		../Qt/5.12.6/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.12.6/clang_64/mkspecs/common/unix.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/mac.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/macx.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/clang.conf \
		../Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.12.6/clang_64/mkspecs/qconfig.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/qt.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/resources.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/moc.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/uic.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.12.6/clang_64/mkspecs/features/lex.prf \
		TestSetCreator.pro \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Qt/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile TestSetCreator.pro -spec macx-clang CONFIG+=x86_64
../Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.12.6/clang_64/mkspecs/qdevice.pri:
../Qt/5.12.6/clang_64/mkspecs/features/device_config.prf:
../Qt/5.12.6/clang_64/mkspecs/common/unix.conf:
../Qt/5.12.6/clang_64/mkspecs/common/mac.conf:
../Qt/5.12.6/clang_64/mkspecs/common/macx.conf:
../Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf:
../Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.12.6/clang_64/mkspecs/common/clang.conf:
../Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.12.6/clang_64/mkspecs/qconfig.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf:
../Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.12.6/clang_64/mkspecs/features/default_post.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf:
../Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.12.6/clang_64/mkspecs/features/qt.prf:
../Qt/5.12.6/clang_64/mkspecs/features/resources.prf:
../Qt/5.12.6/clang_64/mkspecs/features/moc.prf:
../Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.12.6/clang_64/mkspecs/features/uic.prf:
../Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf:
../Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.12.6/clang_64/mkspecs/features/yacc.prf:
../Qt/5.12.6/clang_64/mkspecs/features/lex.prf:
TestSetCreator.pro:
../Qt/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Qt/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl:
../Qt/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile TestSetCreator.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE

TestSetCreator.app/Contents/PkgInfo: 
	@test -d TestSetCreator.app/Contents || mkdir -p TestSetCreator.app/Contents
	@$(DEL_FILE) TestSetCreator.app/Contents/PkgInfo
	@echo "APPL????" > TestSetCreator.app/Contents/PkgInfo
TestSetCreator.app/Contents/Resources/empty.lproj: 
	@test -d TestSetCreator.app/Contents/Resources || mkdir -p TestSetCreator.app/Contents/Resources
	@touch TestSetCreator.app/Contents/Resources/empty.lproj
	
TestSetCreator.app/Contents/Info.plist: 
	@test -d TestSetCreator.app/Contents || mkdir -p TestSetCreator.app/Contents
	@$(DEL_FILE) TestSetCreator.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.TestSetCreator,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.TestSetCreator,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,TestSetCreator,g" -e "s,@LIBRARY@,TestSetCreator,g" -e "s,\$${EXECUTABLE_NAME},TestSetCreator,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../Qt/5.12.6/clang_64/mkspecs/macx-clang/Info.plist.app >TestSetCreator.app/Contents/Info.plist

all: Makefile \
		TestSetCreator.app/Contents/PkgInfo \
		TestSetCreator.app/Contents/Resources/empty.lproj \
		TestSetCreator.app/Contents/Info.plist TestSetCreator.app/Contents/MacOS/TestSetCreator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h masterjpeg.hpp picturedisplay.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp masterjpeg.cpp picturedisplay.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r TestSetCreator.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=x86_64

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_masterjpeg.cpp moc_picturedisplay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_masterjpeg.cpp moc_picturedisplay.cpp
moc_mainwindow.cpp: mainwindow.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../Qt/5.12.6/clang_64/bin/moc
	/Users/adrian/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/adrian/TestSetCreator/moc_predefs.h -I/Users/adrian/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Users/adrian/TestSetCreator -I/usr/local/include -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/adrian/Qt/5.12.6/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_masterjpeg.cpp: masterjpeg.hpp \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/usr/local/include/jpeglib.h \
		/usr/local/include/jconfig.h \
		/usr/local/include/jmorecfg.h \
		/usr/local/include/jerror.h \
		moc_predefs.h \
		../Qt/5.12.6/clang_64/bin/moc
	/Users/adrian/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/adrian/TestSetCreator/moc_predefs.h -I/Users/adrian/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Users/adrian/TestSetCreator -I/usr/local/include -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/adrian/Qt/5.12.6/clang_64/lib masterjpeg.hpp -o moc_masterjpeg.cpp

moc_picturedisplay.cpp: picturedisplay.hpp \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qrect.h \
		moc_predefs.h \
		../Qt/5.12.6/clang_64/bin/moc
	/Users/adrian/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/adrian/TestSetCreator/moc_predefs.h -I/Users/adrian/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Users/adrian/TestSetCreator -I/usr/local/include -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/adrian/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/adrian/Qt/5.12.6/clang_64/lib picturedisplay.hpp -o moc_picturedisplay.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../Qt/5.12.6/clang_64/bin/uic \
		picturedisplay.hpp \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qrect.h
	/Users/adrian/Qt/5.12.6/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp ../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QString \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/usr/local/include/jpeglib.h \
		/usr/local/include/jconfig.h \
		/usr/local/include/jmorecfg.h \
		/usr/local/include/jerror.h \
		masterjpeg.hpp \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qimage.h \
		mainwindow.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		picturedisplay.hpp \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

masterjpeg.o: masterjpeg.cpp ../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QString \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qimage.h \
		/usr/local/include/jpeglib.h \
		/usr/local/include/jconfig.h \
		/usr/local/include/jmorecfg.h \
		/usr/local/include/jerror.h \
		masterjpeg.hpp \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qrect.h \
		mainwindow.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o masterjpeg.o masterjpeg.cpp

picturedisplay.o: picturedisplay.cpp ../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QPointF \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		picturedisplay.hpp \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o picturedisplay.o picturedisplay.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_masterjpeg.o: moc_masterjpeg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_masterjpeg.o moc_masterjpeg.cpp

moc_picturedisplay.o: moc_picturedisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_picturedisplay.o moc_picturedisplay.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

